default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['pg_host'] || '127.0.0.1' %>
  username: <%= ENV['pg_user'] || 'root' %>
  password: <%= ENV['pg_pass'] %>

development:
  <<: *default
  database: tweets_development

test:
  <<: *default
  database: tweets_test

production:
  <<: *default
  database: tweets_production
